In [1]:
import numpy as np

### 1) Alturas  
i. No trecho de código abaixo, crie um ndarray chamado ```altura_em_centimetros``` transformando a lista ```lista_de_alturas``` em um ndarray do numpy com a função ```np.array()```  
ii. Crie um outro objeto ```altura_em_metros```, com os valores de ```altura_em_centimetros``` convertidos para metros.

Alturas i

In [107]:
# i) Lista de alturas em centímetros, variando de 170 a 185, com um incremento de 5 cm
lista_de_centimetros = list(range(170, 190, 5))
lista_de_centimetros

[170, 175, 180, 185]

In [109]:
# Converte a lista de alturas em centímetros para um array numpy
altura_em_centimetros = np.array(lista_de_centimetros)
altura_em_centimetros

array([170, 175, 180, 185])

In [ ]:
Alturas ii

In [112]:
# ii) Converte as alturas de centímetros para metros, dividindo por 100
altura_em_metros = altura_em_centimetros / 100
altura_em_metros

array([1.7 , 1.75, 1.8 , 1.85])

### 2) IMC  
i. Considere que pesos em Kg dessas pessoas, na mesma ortem, estão na lista pesos ```lista_pesos = [70, 75, 80, 85]```. Crie um **ndarray** chamado ```pesos``` com a função ```np.array()``` que contenha esses valores.  
ii. Utilizando o objeto que contém as alturas em metros e esse objeto que contém os respectivos pesos em quilos, calcule o IMC desses indivíduos utilizando a aritmética de arrays e guarde os resultados em um objeto chamado ```imc```.

IMC i

In [114]:
# i) Definir pesos
lista_pesos = [70, 75, 80, 85]

# Definir alturas
lista_alturas = [1.70, 1.75, 1.80, 1.85]

In [116]:
# Criar arrays numpy "pesos"
pesos = np.array(lista_pesos)
pesos

array([70, 75, 80, 85])

In [118]:
# Criar arrays numpy "alturas"
alturas = np.array(lista_alturas)
alturas

array([1.7 , 1.75, 1.8 , 1.85])

IMC ii

In [120]:
# ii) Calculando o IMC
imc = pesos / (alturas ** 2)
imc

array([24.22145329, 24.48979592, 24.69135802, 24.83564646])

### 3) Endividamento

Cálculos de novas variáveis como endividamento total e comprometimento de renda são essenciais para a construção de modelos financeiros em ciência de dados. Áreas não financeiras terão cálculos semelhantes também. Vamos praticar:

Considere que o seguinte ndarray contém os dados de 4 pessoas, total a ser pago a empréstimos mensalmente e renda familiar:

| custo fixo | dívida financeira | renda familiar |
|:----:|:----:|:---|
| 3000  | 1000 | 6000 |
| 2500  | 2500 | 5500 |
| 1000  | 3000 | 7000 |
| 10000 | 5000 | 16000 |

i. Transforme a lista de listas ```dados_financeiros``` no ndarray ```nd_financeiros```.
> ``` dados_financeiros[[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]] ```

ii. Utilize o método ```.transpose ``` e certifique-se de que esse ndarray tenha uma linha por indivíduo e uma coluna por informação. Utilizando a indexação do numpy, imprima no output a segunda linha do array, depois a segunda coluna.

iii. Pratique aritmética com nearrays e calcule o endividamento total como:
$$endividamento\hspace{.2cm}total = \frac{custo \hspace{.2cm}fixo + dívida\hspace{.2cm}financeira}{renda\hspace{.2cm}familiar}$$
Guarde os resultados em uma variável chamada ```endividamento_total``` e verifique os resultados imprimindo o conteúdo dessa variável no output.

iv. Considere que há um erro de digitação que precisa ser corrigido: 3o indivíduo na verdade não possui renda familiar de R\\$7.000,00, mas sim R\\$ 10.000,00. Corrija esse valor e refaça os cálculos.

Endividamento 3-i

In [69]:
# 3-i) lista dados_financeiros
dados_financeiros = [[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]]
dados_financeiros

# transforme essa lista em um ndarray
nd_financeiros = np.array(dados_financeiros)
nd_financeiros

array([[ 3000,  2500,  1000, 10000],
       [ 1000,  2500,  3000,  5000],
       [ 6000,  5500,  7000, 16000]])

Endividamento 3-ii

In [122]:
# 3-ii) transposto o ndarray
nd_financeiros_transposto = nd_financeiros.transpose()

# Imprimindo o ndarray transposto
print(nd_financeiros_transposto)

# Imprimindo a segunda linha (dados do segundo indivíduo)
print("Segunda linha (segundo indivíduo):", nd_financeiros_transposto[1])

# Imprimindo a segunda coluna (dívida financeira)
print("Segunda coluna (dívida financeira):", nd_financeiros_transposto[:, 1])

[[ 3000  1000  6000]
 [ 2500  2500  5500]
 [ 1000  3000  7000]
 [10000  5000 16000]]
Segunda linha (segundo indivíduo): [2500 2500 5500]
Segunda coluna (dívida financeira): [1000 2500 3000 5000]


Endividamento 3-iii

In [73]:
# 3-iii) Calculando o endividamento total (soma das duas primeiras colunas)
endividamento_total = nd_financeiros_transposto[:, 0:2].sum(axis=1)

# Imprimindo o resultado
endividamento_total

array([ 4000,  5000,  4000, 15000])

In [75]:
# Calculando o endividamento total como proporção % da renda
endividamento_total_proporcional = (nd_financeiros_transposto[:, 0:2].sum(axis=1)) / nd_financeiros_transposto[:, 2]

In [77]:
# Imprimindo o resultado
for i, valor in enumerate(endividamento_total_proporcional):
    print(f"Indivíduo {i+1}: {valor:.2%} do total da renda")

Indivíduo 1: 66.67% do total da renda
Indivíduo 2: 90.91% do total da renda
Indivíduo 3: 57.14% do total da renda
Indivíduo 4: 93.75% do total da renda


Endividamento 3-iv

In [81]:
# 3-iv) corrigindo um valor específico, do terceiro indivíduo ( renda familiar de 7.000 para 10.000 )
nd_financeiros_transposto = np.array([[3000, 1000, 6000],
                                    [2500, 2500, 5500],
                                    [1000, 3000, 10000],  # Corrigido para 10.000
                                    [10000, 5000, 16000]])

# Calculando o endividamento total como proporção % da renda
endividamento_total_proporcional = (nd_financeiros_transposto[:, 0:2].sum(axis=1)) / nd_financeiros_transposto[:, 2]

# Imprimindo o resultado 
for i, valor in enumerate(endividamento_total_proporcional):
    print(f"Indivíduo {i+1}: {valor:.2%} do total da renda")

Indivíduo 1: 66.67% do total da renda
Indivíduo 2: 90.91% do total da renda
Indivíduo 3: 40.00% do total da renda
Indivíduo 4: 93.75% do total da renda


### 4) É muito comum precisarmos identificar valores especiais e darmos tratamento a eles quer seja alterando-os quer seja descartando-os. 

O trecho de código abaixo gera um ndarray com números pseudo aleatórios. Considere que para efeitos do estudo que virá, devemos desconsiderar valores iguais a zero. Sendo assim:

i) crie um objeto ```bool_zero``` que traga uma sequencia de booleanos do mesmo tamanho que o objeto poi, e que vale ```True``` quando o valor de ```poi``` é zero, e ```False``` caso contrário.

ii) Conte quantos valores zero existem. Lembre-se de que no final das contas, ```True``` vale 1 para o Python, e ```False``` vale zero, então uma boa dica seria usar a função ```sum()```.

iii) Utilize a indexação booleana que você aprendeu para criar uma variável ```poi_nao_zero``` que aponta para os elementos de ```poi``` diferentes de zero. Dica: você vai pode inverter os elementos do objeto que criou em *ii)* ou escrever a comparação adequada.

In [83]:
# objeto poi - obs: o comando np.random.seed(1234) garante que o mesmo resultado será gerado sempre
np.random.seed(1234)
poi = np.random.poisson(3, 100)
poi

array([3, 3, 6, 2, 4, 5, 4, 4, 2, 0, 3, 3, 2, 8, 2, 3, 3, 3, 0, 4, 4, 2,
       6, 6, 0, 3, 4, 3, 5, 2, 1, 3, 2, 2, 3, 2, 4, 4, 5, 7, 3, 5, 3, 3,
       2, 2, 3, 6, 2, 2, 4, 3, 5, 2, 5, 3, 0, 2, 1, 1, 4, 4, 4, 6, 2, 4,
       1, 2, 5, 5, 3, 4, 1, 4, 1, 1, 7, 1, 2, 1, 3, 7, 0, 4, 4, 0, 6, 1,
       3, 4, 2, 5, 4, 5, 5, 3, 4, 6, 8, 2])

Exercício 4-i

In [97]:
# i) Configurando a semente aleatória
np.random.seed(1234)

# Gerando o ndarray
poi = np.random.poisson(3, 100)

# Criando o array booleano para identificar zeros
bool_zero = poi == 0

# Imprimindo os resultados para verificação
print(poi)
print(bool_zero)

[3 3 6 2 4 5 4 4 2 0 3 3 2 8 2 3 3 3 0 4 4 2 6 6 0 3 4 3 5 2 1 3 2 2 3 2 4
 4 5 7 3 5 3 3 2 2 3 6 2 2 4 3 5 2 5 3 0 2 1 1 4 4 4 6 2 4 1 2 5 5 3 4 1 4
 1 1 7 1 2 1 3 7 0 4 4 0 6 1 3 4 2 5 4 5 5 3 4 6 8 2]
[False False False False False False False False False  True False False
 False False False False False False  True False False False False False
  True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False  True False False False
 False False False False False False False False False False False False
 False False False False False False False False False False  True False
 False  True False False False False False False False False False False
 False False False False]


Exercício 4-ii

In [91]:
# ii) Contando a qtde de zeros usando a função sum()
num_zeros = bool_zero.sum()
print("Número de zeros:", num_zeros)

Número de zeros: 6


Exercício 4-iii

In [105]:
# iii) Criando um array booleano para identificar os NÃO zeros
bool_nao_zero = ~bool_zero

# Criando um novo array com os elementos não-zero
poi_nao_zero = poi[bool_nao_zero]

# Imprimindo resultado
print("Elementos não-zero:", poi_nao_zero)

Elementos não-zero: [3 3 6 2 4 5 4 4 2 3 3 2 8 2 3 3 3 4 4 2 6 6 3 4 3 5 2 1 3 2 2 3 2 4 4 5 7
 3 5 3 3 2 2 3 6 2 2 4 3 5 2 5 3 2 1 1 4 4 4 6 2 4 1 2 5 5 3 4 1 4 1 1 7 1
 2 1 3 7 4 4 6 1 3 4 2 5 4 5 5 3 4 6 8 2]
